#!/usr/bin/env python3
"""Check that every skill's `fgdh.owner` still resolves on GitHub.

The lifecycle document makes "no reachable owner" a retirement trigger, so it
has to be *detectable* rather than merely stated. A skill nobody knows still
works is unmaintained, and an unmaintained skill is trusted at exactly the
moment it is loaded.

Two design decisions worth not undoing:

*   **This is not part of `build_index.py`.** That script is required to be
    deterministic and offline because `--check` compares generated bytes; a
    network call there would make CI results depend on GitHub's availability and
    on rate limits.
*   **It runs weekly, not on every pull request.** A contributor's merge must not
    be blocked by an unrelated owner having left the organization.

Owners are read from `skills/index.json` rather than by re-parsing the skills:
one source, already validated.

`unverifiable` is not a failure. An unauthenticated or rate-limited run must
degrade to a clear "could not check" rather than a false accusation — and a team
lookup without a token cannot distinguish "does not exist" from "is private", so
it reports `unverifiable` by construction.

Usage:
    python scripts/check_owners.py --report    # always exit 0
    python scripts/check_owners.py --strict    # exit 1 on `not-found` only
    python scripts/check_owners.py --json      # machine-readable report on stdout

Exit codes:
    0  reported (always, unless --strict found a `not-found`)
    1  --strict and at least one owner did not resolve
    2  internal error
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "skills" / "index.json"
OWNER_KEY = "fgdh.owner"

API = "https://api.github.com"
USER_AGENT = "fgdh-agent-skills-owners/1 (+github.com/forschungsgruppe-digital-health/agent-skills)"
TIMEOUT_SECONDS = 20

RESOLVED = "resolved"
NOT_FOUND = "not-found"
UNVERIFIABLE = "unverifiable"


def token() -> str | None:
    for name in ("GITHUB_TOKEN", "GH_TOKEN"):
        value = os.environ.get(name)
        if value:
            return value
    return None


def api_get(path: str) -> tuple[int, str | None]:
    """Return (status, error). 200 means it resolved."""
    request = urllib.request.Request(
        f"{API}{path}",
        headers={"User-Agent": USER_AGENT, "Accept": "application/vnd.github+json"},
    )
    auth = token()
    if auth:
        request.add_header("Authorization", f"Bearer {auth}")
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:  # noqa: S310
            return response.status, None
    except urllib.error.HTTPError as exc:
        return exc.code, f"HTTP {exc.code} {exc.reason}"
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return 0, f"cannot reach the GitHub API: {exc}"


def resolve(owner: str) -> dict:
    """Resolve one `@handle` or `@org/team`."""
    result = {"owner": owner, "kind": None, "status": UNVERIFIABLE, "detail": None}

    if not owner.startswith("@"):
        result["status"] = NOT_FOUND
        result["detail"] = "does not start with '@'; not a GitHub handle or team"
        return result

    body = owner[1:]

    if "/" in body:
        result["kind"] = "team"
        org, _, team = body.partition("/")
        if not token():
            result["detail"] = (
                "team lookup needs a token with read:org. Without one, a private team is "
                "indistinguishable from a missing one, so this is not reported as missing."
            )
            return result
        status, error = api_get(f"/orgs/{org}/teams/{team}")
        if status == 200:
            result["status"] = RESOLVED
        elif status == 404:
            result["status"] = NOT_FOUND
            result["detail"] = "no such team, or the token cannot see it"
        else:
            result["detail"] = error
        return result

    result["kind"] = "user"
    status, error = api_get(f"/users/{body}")
    if status == 200:
        result["status"] = RESOLVED
    elif status == 404:
        result["status"] = NOT_FOUND
        result["detail"] = "no such GitHub user"
    elif status in (403, 429):
        result["detail"] = f"rate limited or forbidden ({error}); could not check"
    else:
        result["detail"] = error
    return result


def collect_owners() -> list[tuple[str, list[str]]]:
    """Return [(owner, [skill names])], sorted, deduplicated."""
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    grouped: dict[str, list[str]] = {}
    for skill in index.get("skills", []):
        owner = (skill.get("metadata") or {}).get(OWNER_KEY)
        name = (skill.get("frontmatter") or {}).get("name", "?")
        if owner:
            grouped.setdefault(owner, []).append(name)
    return sorted((owner, sorted(names)) for owner, names in grouped.items())


def render_issue_body(unresolved: list[dict], skills_by_owner: dict[str, list[str]]) -> str:
    lines = [
        "<!-- watch-id: owner-resolution -->",
        "",
        "One or more skill owners no longer resolve on GitHub.",
        "",
        "| Owner | Kind | Skills | Detail |",
        "| --- | --- | --- | --- |",
    ]
    for item in unresolved:
        skills = ", ".join(f"`{name}`" for name in skills_by_owner.get(item["owner"], []))
        lines.append(
            f"| `{item['owner']}` | {item['kind'] or '?'} | {skills} | {item['detail'] or ''} |"
        )
    lines += [
        "",
        "### What this obliges",
        "",
        "A handle can fail to resolve for reasons other than departure, so this starts a "
        "**30-day reassignment window** rather than a retirement.",
        "",
        "- [ ] Confirm whether the owner has actually left.",
        "- [ ] Reassign each affected skill: update `fgdh.owner` **and** the matching "
        "`CODEOWNERS` line, in the same pull request.",
        "- [ ] If no owner can be found within 30 days, begin retirement — deprecate first, "
        "remove a release later. See `docs/lifecycle.md`.",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check that every fgdh.owner still resolves.")
    parser.add_argument("--report", action="store_true", help="report and always exit 0")
    parser.add_argument("--strict", action="store_true", help="exit 1 on `not-found`")
    parser.add_argument("--json", dest="as_json", action="store_true", help="JSON on stdout")
    args = parser.parse_args(argv)

    try:
        owners = collect_owners()
    except (OSError, ValueError) as exc:
        print(f"internal error: cannot read {INDEX_PATH}: {exc}", file=sys.stderr)
        return 2

    if not owners:
        print("no owners in the index; nothing to check")
        return 0

    skills_by_owner = dict(owners)
    results = [resolve(owner) for owner, _ in owners]
    unresolved = [r for r in results if r["status"] == NOT_FOUND]

    if args.as_json:
        json.dump(
            {
                "results": results,
                "skills_by_owner": skills_by_owner,
                "issue_title": "spec-watch: skill owners no longer resolve",
                "issue_body": (
                    render_issue_body(unresolved, skills_by_owner) if unresolved else None
                ),
            },
            sys.stdout,
            indent=2,
            ensure_ascii=False,
        )
        sys.stdout.write("\n")
    else:
        width = max(len(owner) for owner, _ in owners)
        for result in results:
            skills = ", ".join(skills_by_owner.get(result["owner"], []))
            detail = f"  ({result['detail']})" if result["detail"] else ""
            print(f"{result['owner']:<{width}}  {result['status']:<12}  {skills}{detail}")
        counts = {status: sum(1 for r in results if r["status"] == status) for status in
                  (RESOLVED, NOT_FOUND, UNVERIFIABLE)}
        print()
        print(f"{len(results)} owner(s): {counts[RESOLVED]} resolved, "
              f"{counts[NOT_FOUND]} not found, {counts[UNVERIFIABLE]} unverifiable")
        if counts[UNVERIFIABLE] and not token():
            print("no GITHUB_TOKEN in the environment; team lookups cannot be checked")

    if args.strict and unresolved:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
